config/routes.rb
Birdytrainer::Application.routes.draw do
  resources :birdy_voices
  resource :trainer, :only => [] do
    collection do
      get "ask"
      post "check"
    end
  end
root :to => 'trainers#ask'

end

app/models/birdy_voice.rb
class BirdyVoice < ActiveRecord::Base
  mount_uploader :voice, VoiceUploader
  attr_accessible :name, :voice
 
  def self.random
  	ids=BirdyVoice.all.map{|birdy_voice| birdy_voice.id}
	anzahl=ids.size
	zufall=rand(anzahl)
	bird_id=ids[zufall]
	BirdyVoice.find(bird_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/birdy_voices_controller.rb
class BirdyVoicesController < ApplicationController
  # GET /birdy_voices
  # GET /birdy_voices.json
  def index
    @birdy_voices = BirdyVoice.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @birdy_voices }
    end
  end

  # GET /birdy_voices/1
  # GET /birdy_voices/1.json
  def show
    @birdy_voice = BirdyVoice.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @birdy_voice }
    end
  end

  # GET /birdy_voices/new
  # GET /birdy_voices/new.json
  def new
    @birdy_voice = BirdyVoice.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @birdy_voice }
    end
  end

  # GET /birdy_voices/1/edit
  def edit
    @birdy_voice = BirdyVoice.find(params[:id])
  end

  # POST /birdy_voices
  # POST /birdy_voices.json
  def create
    @birdy_voice = BirdyVoice.new(params[:birdy_voice])

    respond_to do |format|
      if @birdy_voice.save
        format.html { redirect_to @birdy_voice, notice: 'Birdy voice was successfully created.' }
        format.json { render json: @birdy_voice, status: :created, location: @birdy_voice }
      else
        format.html { render action: "new" }
        format.json { render json: @birdy_voice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /birdy_voices/1
  # PUT /birdy_voices/1.json
  def update
    @birdy_voice = BirdyVoice.find(params[:id])

    respond_to do |format|
      if @birdy_voice.update_attributes(params[:birdy_voice])
        format.html { redirect_to @birdy_voice, notice: 'Birdy voice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @birdy_voice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /birdy_voices/1
  # DELETE /birdy_voices/1.json
  def destroy
    @birdy_voice = BirdyVoice.find(params[:id])
    @birdy_voice.destroy

    respond_to do |format|
      format.html { redirect_to birdy_voices_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/trainer_controller.rb
class TrainerController < ApplicationController
	def ask
    @birdyvoice=BirdyVoice.find(1)
	end

	protected


end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
	def ask
    @birdyvoice=BirdyVoice.random
	end

	def check
	  @birdyvoice=BirdyVoice.find(params[:id])
	  if @birdyvoice.name == params[:name] 
	    redirect_to(ask_trainer_path, :notice => 'richtig!')
	  else
      redirect_to(ask_trainer_path, :error => "falsch, es war ein #{@birdyvoice.name}")
    end      
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/birdy_voices_helper.rb
module BirdyVoicesHelper
end

app/views/birdy_voices/_birdy_player.html.erb
<audio controls height="100" width="100">
  <source src="<%= mp3file %>" type="audio/mpeg">
  <embed height="50" width="100" src="<%= mp3file %>">
</audio>

app/views/birdy_voices/_form.html.erb
<%= form_for(@birdy_voice, :html => {:multipart => true}) do |f| %>
  <% if @birdy_voice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@birdy_voice.errors.count, "error") %> prohibited this birdy_voice from being saved:</h2>

      <ul>
      <% @birdy_voice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :voice %><br />
    <%= f.file_field :voice %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/birdy_voices/edit.html.erb
<h1>Editing birdy_voice</h1>

<%= render 'form' %>

<%= link_to 'Show', @birdy_voice %> |
<%= link_to 'Back', birdy_voices_path %>

app/views/birdy_voices/index.html.erb
<h1>Listing birdy_voices</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Voice</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @birdy_voices.each do |birdy_voice| %>
  <tr>
    <td><%= birdy_voice.name %></td>
    <td><%= render "birdy_player", :mp3file => birdy_voice.voice %></td>
    <td><%= link_to 'Show', birdy_voice %></td>
    <td><%= link_to 'Edit', edit_birdy_voice_path(birdy_voice) %></td>
    <td><%= link_to 'Destroy', birdy_voice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Birdy voice', new_birdy_voice_path %>

app/views/birdy_voices/new.html.erb
<h1>New birdy_voice</h1>

<%= render 'form' %>

<%= link_to 'Back', birdy_voices_path %>

app/views/birdy_voices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @birdy_voice.name %>
</p>

<p>
  <b>Voice:</b>
 <%= render "birdy_player", :mp3file => @birdy_voice.voice %>
 </p>


<%= link_to 'Edit', edit_birdy_voice_path(@birdy_voice) %> |
<%= link_to 'Back', birdy_voices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Birdytrainer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= content_tag :p, notice, :id=> "notice" %>
	<%= content_tag :p, notice, :id=> "error" %>
<%= yield %>

</body>
</html>

app/views/trainer/ask.html.erb
<h2>Welche Vogelstimme ist das?</h2>
<%= render "birdy_voices/birdy_player", :mp3file => @birdyvoice.voice %>

<%= form_tag(check_trainer_index_path) do %>
<%= text_field_tag 'birdname' %>
<%= submit_tag 'prüfen' %>

<% end %>

app/views/trainers/ask.html.erb
<h2>Welche Vogelstimme ist das?</h2>
<%= render "birdy_voices/birdy_player", :mp3file => @birdyvoice.voice %>

<%= form_tag(check_trainer_path) do %>
<%= text_field_tag 'birdname' %>
<%= text_field_tag 'id',@birdyvoice.id, :hidden =>true %>
<%= submit_tag 'prüfen' %>

<% end %>